# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "web.virtual.it-elementary"
  config.vm.box_url = "./web.virtual.it-elementary_0.1.0.box"
  
 	#config.vm.network :private_network, ip: "192.168.56.151"
	#config.vm.hostname = "mypacker.dev"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  # config.ssh.private_key_path = "../keys/id_rsa.ppk"
  # config.ssh.insert_key = true

  config.vm.synced_folder '../conf', '/home/vagrant/conf', create: true

#
#  config.vm.define :virtualbox do |virtualbox|
#    virtualbox.vm.hostname = "virtualbox-ubuntu1604"
#    virtualbox.vm.box = "file://web.virtual.it-elementary_0.1.0.box"
#    virtualbox.vm.network :private_network, ip: "172.16.3.2"
#
#    virtualbox.ssh.private_key_path = "../keys/id_rsa.ppk"
#  end
#

  config.vm.provider :virtualbox do |v|
    v.gui = false
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision "shell", inline: "echo Hello, World"
end
